---
# task for install lb-install

- name: LB-INSTALL | Copy template config file for load balance node
  template:
    src: "{{ role_path }}/templates/lb-config.cfg.j2"
    dest: /root/lb-config.cfg
    mode: 'u+x'

- name: LB-INSTALL | Generate ssh key
  command: 'ssh-keygen -t rsa -f /root/.ssh/id_rsa -q -P ""'

- name: LB-INSTALL | Install epel repo
  yum: name='epel-release' state=installed

- name: LB-INSTALL | Install sshpass, vim and wget
  yum: name='{{ item }}' state=installed
  with_items:
    - sshpass
    - vim
    - wget

- name: LB-INSTALL | Copy ssh key from lb1 to lb2
  command: 'sshpass -p "{{ ansible_ssh_pass }}" ssh-copy-id -o StrictHostKeyChecking=no -i /root/.ssh/id_rsa.pub root@{{ LB2_IP_NIC3 }}'
  become: true
  when: HOST_NAME == LB1_HOSTNAME

- name: LB-INSTALL | Install proxy
  shell: '{{ item }}'
  with_items:
    - 'echo "proxy=http://123.30.178.220:3142" >> /etc/yum.conf'
    - 'yum -y update'

- name: LB-INSTALL | Install repo newton
  shell: '{{ item }}'
  with_items:
    - 'yum -y install centos-release-openstack-newton'
    - 'yum -y upgrade'

- name: LB-INSTALL | Add host name and ip to hosts file
  shell: '{{ item }}'
  with_items:
    - 'source /root/lb-config.cfg'
    - 'echo "{{ LB1_IP_NIC2 }} {{ LB1_HOSTNAME }}" >> /etc/hosts'
    - 'echo "{{ LB2_IP_NIC2 }} {{ LB2_HOSTNAME }}" >> /etc/hosts'

- name: LB-INSTALL | Copy config repo for nginx
  template: src='{{ role_path }}/templates/nginx.repo.j2' dest='/etc/yum.repos.d/nginx.repo'

- name: LB-INSTALL | Install nginx
  yum: name='nginx' state=installed

- name: LB-INSTALL | Start nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: LB-INSTALL | Copy template file for nginx
  template: src='{{ role_path }}/templates/index.html.j2' dest='/usr/share/nginx/html/index.html'

- name: LB-INSTALL | Restart nginx
  service: name=nginx state=restarted

- name: LB-INSTALL | Coppy file nginx.cnf to nginx.cnf.orig
  command: 'cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.orig'

## Install pacemaker
- name: LB-INSTALL | Install pacemaker and pcs
  yum: name='{{ item }}' state=installed
  with_items:
    - pacemaker
    - pcs

- name: LB-INSTALL | Start pcsd
  service:
    name: pcsd
    state: started
    enabled: yes

- name: LB-INSTALL | Echo PASS_CLUSTER to ha cluster
  shell: 'echo {{ PASS_CLUSTER }} | passwd --stdin hacluster'

- name: LB-INSTALL | Config cluster
  shell: '{{ item }}'
  with_items:
    - 'source /root/lb-config.cfg'
    - 'pcs cluster auth {{ LB1_HOSTNAME }} {{ LB2_HOSTNAME }} -u hacluster -p {{ PASS_CLUSTER }} --force'
    - 'pcs cluster setup --name ha_cluster {{ LB1_HOSTNAME }} {{ LB2_HOSTNAME }}'
    - 'pcs cluster start --all'
    - 'pcs cluster enable --all'
    - 'pcs property set stonith-enabled=false'
    - 'pcs property set default-resource-stickiness="INFINITY"'
  when: HOST_NAME == LB1_HOSTNAME