---
version: '3.2'
services:
    elasticsearch:
        image: ${ELASTICSEARCH_IMAGE}
        restart: always
        environment:
            - 'node.name=HEYJUDE'
            - 'discovery.type=single-node'
            - 'bootstrap.memory_lock=true'
            - 'ES_JAVA_OPTS=-Xms256m -Xmx256m'
        ports:
            - 9200:9200
        volumes:
            - type: bind
              source: /var/lib/elasticsearch
              target: /usr/share/elasticsearch/data


    # kibana:
    #     image: ${KIBANA_IMAGE}
    #     restart: always
    #     depends_on:
    #         - elasticsearch


    fluentd:
        build: .
        ports:
            - 127.0.0.1:24224:24224
            - 0.0.0.0:5140:5140/udp
        volumes:
            - ./fluentd/etc:/fluentd/etc
            - ./fluentd/data:/fluentd/log


    # nginx:
    #     image: ${NGINX_IMAGE}
    #     restart: always
    #     ports:
    #         - 80:80
    #     volumes:
    #         - type: bind
    #           source: ./nginx/nginx.conf
    #           target: /etc/nginx/nginx.conf
    #           read_only: true
    #         - type: bind
    #           source: ./nginx/conf.d
    #           target: /etc/nginx/conf.d
    #           read_only: true
    #     depends_on:
    #         - kibana

