- name: COM | PREPARE | Install proxy
  lineinfile:
    path: /etc/yum.conf 
    line: 'proxy=http://123.30.178.220:3142'

- name: COM | PREPARE | upgrade all packages
  yum:
    name: '*'
    state: latest

- name: COM | PREPARE | Create file /etc/yum.repos.d/MariaDB.repo
  file: 
    path: /etc/yum.repos.d/MariaDB.repo
    state: touch

- name: COM | PREPARE | Install repo galera
  blockinfile:
    path: /etc/yum.repos.d/MariaDB.repo
    block: |
        [mariadb]
        name = MariaDB
        baseurl = http://yum.mariadb.org/10.1/centos7-amd64
        gpgkey=https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
        gpgcheck=1

- name: COM | PREPARE | upgrade all packages
  yum:
    name: '*'
    state: latest

- name: COM | PREPARE | Install centos-release-openstack-newton
  yum:
    name: centos-release-openstack-newton
    state: present

- name: COM | PREPARE | upgrade all packages
  yum:
    name: '*'
    state: latest


- name: COM | PREPARE | Install repo for Openstack Newton
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - crudini
    - wget
    - vim
    - python-openstackclient
    - openstack-selinux
    - mariadb
    - mariadb-server
    - python2-PyMySQL

- name: COM | PREPARE | Install declare_host on IP_NIC
  lineinfile:
    path: /etc/hosts
    regexp: '^{{ item.IP_NIC }}'
    line: '{{ item.IP_NIC }}   {{ item.HOST_NAME}}'
  with_items:
    - {IP_NIC: "{{ CTL1_IP_NIC3 }}" , HOST_NAME: "{{ CTL1_HOSTNAME }}"}
    - {IP_NIC: "{{ CTL2_IP_NIC3 }}" , HOST_NAME: "{{ CTL2_HOSTNAME }}"}
    - {IP_NIC: "{{ CTL3_IP_NIC3 }}" , HOST_NAME: "{{ CTL3_HOSTNAME }}"}
    - {IP_NIC: "{{ COM1_IP_NIC4 }}" , HOST_NAME: "{{ COM1_HOSTNAME }}"}


- name: COM | PREPARE | Install chrony
  yum:
    name: chrony
    state: present

- name: COM | PREPARE | Enable and start chrony
  service:
    name: chronyd
    enabled: True
    state: started

- name: COM | PREPARE | Restart chrony
  service:
    name: chronyd
    state: restarted

- name: COM | PREPARE | config file /etc/chrony.conf
  lineinfile:
    path: /etc/chrony.conf
    regexp: '^{{ item }}$'
    line: '#'
  with_items:
    - server 0.centos.pool.ntp.org iburst
    - server 1.centos.pool.ntp.org iburst
    - server 2.centos.pool.ntp.org iburst
    - server 3.centos.pool.ntp.org iburst

- name: COM | PREPARE | config file /etc/chrony.config add ntp server
  lineinfile:
    path: /etc/chrony.conf
    line: "server {{ CTL1_IP_NIC3 }} iburst"

- name: COM | PREPARE | Enable and start chrony
  service:
    name: chronyd
    enabled: True
    state: started

- name: COM | PREPARE | Restart chrony
  service:
    name: chronyd
    state: restarted

- name: CTL | PREPARE | Restart server
  become: yes
  shell: sleep 2 && /sbin/shutdown -r now "Ansible system package upgraded"
  async: 1
  poll: 0
  ignore_errors: true

- name: CTL | PREPARE | waiting 30 secs for server to come back
  local_action: wait_for host={{ ansible_default_ipv4.address }} port=22 state=started delay=60 timeout=180
  become: false
