---
# task for install rabbitmq-bonding

- name: MQ-BONDING | Set hostname
  hostname:
    name: "{{ HOST_NAME }}"

- name: MQ-BONDING | Install epel repo
  yum: name='epel-release' state=installed

- name: MQ-BONDING | Install needed network manager libs
  yum:
    name: '{{ item }}'
    state: installed
  with_items:
    - NetworkManager-glib
    - nm-connection-editor.x86_64
    - libsemanage-python
    - policycoreutils-python

- name: MQ-BONDING | Try nmcli add bond0 and bond1
  nmcli:
    type: bond
    conn_name: "{{ item.bond_name }}"
    ifname: '{{ item.bond_name }}'
    ip4: "{{ item.ip }}/{{ item.netmask }}"
    mode: active-backup
    state: present
    autoconnect: yes
  with_items:
    - {bond_name: '{{ BOND0_NIC }}', ip: '{{ MQ_IP_NIC1 }}', netmask: '{{ BOND0_NETMASK }}'}
    - {bond_name: '{{ BOND1_NIC }}', ip: '{{ MQ_IP_NIC2 }}', netmask: '{{ BOND1_NETMASK }}'}

- name: MQ-BONDING | Config bon1 - add gateway and dns
  nmcli:
    type: bond
    conn_name: "{{ BOND1_NIC }}"
    ifname: '{{ BOND1_NIC }}'
    ip4: "{{ MQ_IP_NIC2 }}/{{ BOND1_NETMASK }}"
    gw4: '{{ BOND1_DEFAULT_GATEWAY }}'
    dns4: '{{ BOND1_DNS }}'
    mode: active-backup
    state: present
    autoconnect: yes

- name: MQ-BONDING | Modify method for ip4
  command: 'nmcli con modify {{ item }} ipv4.method manual'
  with_items:
    - '{{ BOND0_NIC }}'
    - '{{ BOND1_NIC }}'

- name: MQ-BONDING | Ignore ip6
  command: 'nmcli con modify {{ item }} ipv6.method ignore'
  with_items:
    - '{{ BOND0_NIC }}'
    - '{{ BOND1_NIC }}'

- name: MQ-BONDING | Try nmcli add bond-slave for bond0 and bond1
  nmcli:
    type: bond-slave
    conn_name: '{{ item.bond }}-{{ item.interface }}'
    ifname: '{{ item.interface }}'
    master: '{{ item.bond }}'
    state: present
  with_items:
    - {bond: '{{ BOND0_NIC }}', interface: '{{ INTERFACE1 }}'}
    - {bond: '{{ BOND0_NIC }}', interface: '{{ INTERFACE2 }}'}
    - {bond: '{{ BOND1_NIC }}', interface: '{{ INTERFACE3 }}'}
    - {bond: '{{ BOND1_NIC }}', interface: '{{ INTERFACE4 }}'}

- name: MQ-BONDING | Up all bond and interfaces
  command: 'nmcli con up {{ item }}'
  with_items:
    - "{{ BOND0_NIC }}-{{ INTERFACE1 }}"
    - "{{ BOND0_NIC }}-{{ INTERFACE2 }}"
    - "{{ BOND0_NIC }}"
    - "{{ BOND1_NIC }}-{{ INTERFACE3 }}"
    - "{{ BOND1_NIC }}-{{ INTERFACE4 }}"
    - "{{ BOND1_NIC }}"

- name: MQ-BONDING | Replace config in file config of interfaces
  replace:
    path: '/etc/sysconfig/network-scripts/ifcfg-{{ item }}'
    regexp: 'BONDING_OPTS=mode=active-backup'
    replace: 'BONDING_OPTS="mode=active-backup miimon=100"'
  with_items:
    - '{{ BOND0_NIC }}'
    - '{{ BOND1_NIC }}'

- name: MQ-BONDING | Delete 4 interface in nmcli
  nmcli:
    conn_name: '{{ item }}'
    state: absent
  with_items:
    - '{{ INTERFACE1 }}'
    - '{{ INTERFACE2 }}'
    - '{{ INTERFACE3 }}'
    - '{{ INTERFACE4 }}'

- name: MQ-BONDING | Replace config selinux
  replace:
    path: '/etc{{ item }}'
    regexp: 'SELINUX=enforcing'
    replace: 'SELINUX=disabled'
  with_items:
    - '/sysconfig/selinux'
    - '/selinux/config'

- name: MQ-BONDING | Stop services firewall and NetworkManager
  service:
    name: '{{ item }}'
    state: stopped
  with_items:
    - 'firewalld'
    - 'NetworkManager'

- name: MQ-BONDING | Restart service network
  service:
    name: 'network'
    state: restarted

- name: MQ-BONDING | Restart server
  become: yes
  shell: sleep 2 && /sbin/shutdown -r now "Ansible system package upgraded"
  async: 1
  poll: 0
  ignore_errors: true

- name: MQ-BONDING | waiting 30 secs for server to come back
  local_action: wait_for host={{ ansible_default_ipv4.address }} port=22 state=started delay=60 timeout=300
  become: false